BankingApplication/Controllers/CustomerController.cs
using System.Threading.Tasks;
using BankingApplication.Data;
using BankingApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using RepositoryWrapper;
using BankingApplication.Attributes;

namespace BankingApplication.Controllers
{   
    
    [AuthorizeCustomer]
    public class CustomerController : Controller
    {
        //Repository object
        private readonly Wrapper repo;
        public CustomerController(BankAppContext context)
        {
            repo = new Wrapper(context);
        }
        private int CustomerID => HttpContext.Session.GetInt32(nameof(Customer.CustomerID)).Value;

        private async Task<Customer> GetCustomerData() 
        {
            var customer = await repo.Customer.GetByID(x => x.CustomerID == CustomerID).Include(x => x.Accounts).
                FirstOrDefaultAsync();

            return customer;
        }

        // Go to edit profile page.
        public async Task<IActionResult> EditProfile() {
            
           var customer =  await GetCustomerData();

            return View(customer);
        } 

        // Go to change password page.
        public ViewResult ChangePassword() {
            return View();
        } 
        

        // Editing all customer attributes except password.
        [HttpPost]
        public async Task<IActionResult> EditProfile(Customer customer){
            if (ModelState.IsValid)
            {
                repo.Customer.Update(customer);
                await repo.SaveChanges();
                ModelState.AddModelError("EditSuccess", "Profile edited successfully.");
                // Updating session variable storing customer name.
                HttpContext.Session.SetString(nameof(Customer.CustomerName), customer.CustomerName);
            }
            return View(customer);

        }


        // Editing customer's password.
        public async Task<IActionResult> SavePassword(string oldpassword,string newpassword,string confirmnewpassword){
            var userID = HttpContext.Session.GetString(nameof(Login.UserID));
            var login = await repo.Login.GetByID(a => a.UserID == userID).FirstOrDefaultAsync();
            var result = login.ChangePassword(oldpassword, newpassword, confirmnewpassword);
            ModelState.AddModelError(result.Item1, result.Item2);
            await repo.SaveChanges();
            return View("ChangePassword"); 
        }

    }
}

BankingApplication/Controllers/LoginController.cs
using System.Threading.Tasks;
using BankingApplication.Data;
using BankingApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RepositoryWrapper;
using SimpleHashing;

namespace BankingApplication.Controllers
{
    public class LoginController : Controller
    {
        //Repository object
        private readonly Wrapper repo;
        public LoginController(BankAppContext context)
        {
            repo = new Wrapper(context);
        }
        public IActionResult Login()
        {
            return View();
        }

        //Login Form post logic referencing Web Dev Tutorial
        [HttpPost]
        public async Task<IActionResult> Login(string userID, string password)
        {
            //LINQ query for eager loading login
            var login = await repo.Login.GetByID(a => a.UserID == userID).Include(a => a.Customer).FirstOrDefaultAsync();
            if (login == null || !PBKDF2.Verify(login.Password, password))
            {
                ModelState.AddModelError("LoginFailed", "Login failed, please try again.");
                return View(new LoginViewModel { UserID = userID });
            }

            // Set customer session variables
            HttpContext.Session.SetInt32(nameof(Customer.CustomerID), login.CustomerID);
            HttpContext.Session.SetString(nameof(Customer.CustomerName), login.Customer.CustomerName);
            HttpContext.Session.SetString(nameof(BankingApplication.Models.Login.UserID), login.UserID);

            //Redirect to customer page
            return RedirectToAction("Index", "Bank");
        }

        public IActionResult Logout()
        {
            //Clear Session variables
            HttpContext.Session.Clear();

            //Return to home page
            return RedirectToAction("Index", "Home");

        }
    }
    
}

BankingApplication/Controllers/MyStatementsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using BankingApplication.Attributes;
using BankingApplication.Data;
using BankingApplication.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;
using RepositoryWrapper;

namespace BankingApplication.Controllers {
    [AuthorizeCustomer]
    public class MyStatementsController : Controller {
        //Repository object
        private readonly Wrapper repo;
        public MyStatementsController (BankAppContext context) {
            repo = new Wrapper (context);
        }
        private int CustomerID => HttpContext.Session.GetInt32 (nameof (Customer.CustomerID)).Value;
        public async Task<IActionResult> SelectAccount () {
            
            var accounts = await repo.Account.GetByID (x => x.CustomerID == CustomerID).ToListAsync ();

            return View (accounts);
        }

        public IActionResult IndexToMyDetails (int accountNumber) {
            HttpContext.Session.SetInt32 ("selectedAccountNumber", accountNumber);
            return RedirectToAction (nameof (MyDetails));
        }

        // Paging code referenced from web dev tutorials.
        public async Task<IActionResult> MyDetails (int page = 1) {
            // Number of transactions to be shown at a time.
            const int pageSize = 4;
            
            var selectedAccountNumber = HttpContext.Session.GetInt32 ("selectedAccountNumber");
            
            // List of transactions to be paged.
            var pagedList = await repo.Transaction.GetByID (x => x.AccountNumber == selectedAccountNumber).ToPagedListAsync (page, pageSize);

            return View (pagedList);
        }

        // Returning a partial view showing balance and button to view transctions once account
        // is selected on select account page.
        public async Task<IActionResult> SeeMyBalance (int id) {
            var account = await repo.Account.GetByID (x => x.AccountNumber == id).FirstOrDefaultAsync ();
            return PartialView (account);
        }

    }

}

BankingApplication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWBA Banking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BankingApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* Navbar Customization *@
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @{
                            var isLoggedIn = Context.Session.GetInt32(nameof(Customer.CustomerID)).HasValue;
                        }
                        @if (isLoggedIn)
                        {
                        <li class="nav-item">
                            <span class="nav-link text-dark">
                                Welcome, @Context.Session.GetString(nameof(Customer.CustomerName))
                            </span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Login" asp-action="Login">Login</a>
                        </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if(isLoggedIn)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="Index">ATM Page</a>
                        </li>
                        <li class="nav-item">
                            <div class="btn-group">
                                <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">BillPay</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="BillPay" asp-action="CreateBill">Create Bill</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="BillPay" asp-action="SelectAccount">Bill Schedule</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="btn-group">
                                <a class="nav-link text-dark dropdown-toggle" data-toggle="dropdown">Edit Profile</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="EditProfile">Edit Personal Details</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="ChangePassword">Change Password</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MyStatements" asp-action="SelectAccount">My Statements</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <style>
            /*Background Image settings*/
                body {
                    background-image: url(../Images/bank-cartoon.png);
                    background-repeat: no-repeat;
                    background-position: right bottom; 
                }
            </style>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2020 - NWBA Banking
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>